version: '3.1'

services:
    api:
        container_name: nodejsapi
        restart: always
        build: ./dockernodejs
        ports:
            - '3355:3000'
        links:
            - mongodb
    mongodb:
        container_name: mongodbwalmart
        image: mongo:3.6.8
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: productListUser
            MONGO_INITDB_ROOT_PASSWORD: productListPassword
        ports:
            - '27017:27017'
        volumes:
            - ./dockerdb/database/:/home/database
