version: '3'

services:
    api:
        container_name: nodejsapi
        restart: always
        build: ./dockernodejs
        ports:
            - '3355:3000'
        links:
            - mongodb
    mongodb:
        container_name: mongodb-local
        ports:
            - '27017:27017'
